"""
Agent 4: The Archivist – Living Context Maintainer

Produces and maintains the system's output artifacts:
  - CODEBASE.md   : living context file for AI coding agent injection
  - onboarding_brief.md : Day-One brief with Five FDE answers
  - Writes lineage_graph.json and module_graph.json via serialisers
  - cartography_trace.jsonl : maintained by CartographyTracer (logging_utils)
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from src.agents.semanticist import DAY_ONE_QUESTIONS
from src.config import CONFIG
from src.graph.graph_serializers import save_knowledge_graph
from src.graph.knowledge_graph import KnowledgeGraph
from src.utils.logging_utils import get_logger, get_tracer

logger = get_logger(__name__)


class Archivist:
    """Generates and saves all cartography output artifacts."""

    def __init__(
        self,
        repo_root: Path,
        kg: KnowledgeGraph,
        cartography_dir: Path,
        day_one_answers: dict[str, str] | None = None,
        purpose_statements: dict[str, str] | None = None,
        domain_clusters: dict[str, str] | None = None,
        drift_flags: list[str] | None = None,
    ) -> None:
        self.repo_root = repo_root
        self.kg = kg
        self.cartography_dir = cartography_dir
        self.day_one_answers = day_one_answers or {}
        self.purpose_statements = purpose_statements or {}
        self.domain_clusters = domain_clusters or {}
        self.drift_flags = drift_flags or []
        self.tracer = get_tracer()

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    def run(self) -> dict[str, str]:
        """Generate all artifacts. Returns dict of artifact_name → path."""
        self.cartography_dir.mkdir(parents=True, exist_ok=True)

        logger.info("[Archivist] Generating cartography artifacts…")
        artifacts: dict[str, str] = {}

        # 1. Graph JSON files
        save_knowledge_graph(self.kg, self.cartography_dir)
        artifacts["module_graph"] = str(self.cartography_dir / "module_graph.json")
        artifacts["lineage_graph"] = str(self.cartography_dir / "lineage_graph.json")

        # 2. CODEBASE.md
        codebase_path = self.cartography_dir / "CODEBASE.md"
        codebase_path.write_text(self._generate_codebase_md(), encoding="utf-8")
        artifacts["codebase_md"] = str(codebase_path)

        # 3. onboarding_brief.md
        brief_path = self.cartography_dir / "onboarding_brief.md"
        brief_path.write_text(self._generate_onboarding_brief(), encoding="utf-8")
        artifacts["onboarding_brief"] = str(brief_path)

        logger.info(f"[Archivist] Artifacts written to {self.cartography_dir}")

        if self.tracer:
            self.tracer.log(
                agent="Archivist",
                action="artifacts_generated",
                metadata={"artifacts": list(artifacts.keys()), "dir": str(self.cartography_dir)},
            )

        return artifacts

    # ------------------------------------------------------------------
    # CODEBASE.md generation
    # ------------------------------------------------------------------

    def _generate_codebase_md(self) -> str:
        mg = self.kg.module_graph
        lg = self.kg.lineage_graph

        top_modules = mg.top_modules_by_pagerank(5)
        sources = lg.find_sources()
        sinks = lg.find_sinks()
        circular_deps = mg.find_circular_dependencies()
        high_velocity = mg.G.graph.get("high_velocity_files", [])[:10]
        total_modules = mg.G.number_of_nodes()
        total_datasets = len(lg.get_dataset_nodes())

        # Domain breakdown
        domain_breakdown: dict[str, int] = {}
        for path, domain in self.domain_clusters.items():
            domain_breakdown[domain] = domain_breakdown.get(domain, 0) + 1

        # Purpose index (top 20 by PageRank)
        purpose_lines = []
        for path, _ in mg.top_modules_by_pagerank(20):
            stmt = self.purpose_statements.get(path) or mg.G.nodes.get(path, {}).get("purpose_statement", "")
            if stmt:
                purpose_lines.append(f"- **`{path}`**: {stmt}")

        lines = [
            "# CODEBASE.md — Living Architecture Context",
            f"> Auto-generated by Brownfield Cartographer on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            f"> Repository: `{self.repo_root.name}`",
            "",
            "---",
            "",
            "## Architecture Overview",
            "",
            f"This codebase contains **{total_modules} modules** across "
            f"{len(set(self.domain_clusters.values()))} inferred business domains "
            f"and **{total_datasets} tracked datasets**.",
            "",
        ]

        if domain_breakdown:
            lines += [
                "**Domain breakdown:**",
                "",
            ]
            for domain, count in sorted(domain_breakdown.items(), key=lambda x: -x[1]):
                lines.append(f"- {domain}: {count} modules")
            lines.append("")

        lines += [
            "---",
            "",
            "## Critical Path",
            "",
            "_Top 5 modules by PageRank (most-imported architectural hubs):_",
            "",
        ]
        for i, (path, score) in enumerate(top_modules, 1):
            purpose = self.purpose_statements.get(path, "")
            lines.append(f"{i}. **`{path}`** (PageRank={score:.4f})")
            if purpose:
                lines.append(f"   > {purpose}")
        lines.append("")

        lines += [
            "---",
            "",
            "## Data Sources & Sinks",
            "",
            "**Sources** (data enters the system here — no upstream producers):",
            "",
        ]
        for src in sources[:10]:
            lines.append(f"- `{src}`")
        if not sources:
            lines.append("- _(none detected)_")

        lines += [
            "",
            "**Sinks** (terminal outputs — nothing downstream consumes these):",
            "",
        ]
        for sink in sinks[:10]:
            lines.append(f"- `{sink}`")
        if not sinks:
            lines.append("- _(none detected)_")

        lines += [
            "",
            "---",
            "",
            "## Known Debt",
            "",
        ]

        if circular_deps:
            lines.append("**⚠️ Circular Dependencies:**")
            lines.append("")
            for group in circular_deps[:5]:
                lines.append(f"- {' → '.join(group)}")
            lines.append("")

        if self.drift_flags:
            lines.append("**📄 Documentation Drift** _(LLM purpose ≠ existing docstring):_")
            lines.append("")
            for path in self.drift_flags[:10]:
                lines.append(f"- `{path}`")
            lines.append("")

        if not circular_deps and not self.drift_flags:
            lines.append("_No significant debt detected._")
            lines.append("")

        lines += [
            "---",
            "",
            "## High-Velocity Files",
            "",
            f"_Files with most commits in last {CONFIG.analysis.git_velocity_days} days — likely pain points:_",
            "",
        ]
        for f in high_velocity:
            vel = self.kg.module_graph.G.nodes.get(f, {}).get("change_velocity_30d", "?")
            lines.append(f"- `{f}` ({vel} commits)")
        if not high_velocity:
            lines.append("- _(git history not available)_")

        lines += [
            "",
            "---",
            "",
            "## Module Purpose Index",
            "",
            "_Top 20 modules by architectural centrality with purpose statements:_",
            "",
        ]
        lines += purpose_lines or ["_(LLM analysis not run — use `--static-only false` to enable)_"]
        lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Onboarding brief generation
    # ------------------------------------------------------------------

    def _generate_onboarding_brief(self) -> str:
        mg = self.kg.module_graph
        lg = self.kg.lineage_graph

        lines = [
            "# FDE Day-One Onboarding Brief",
            "",
            f"> Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            f"> Repository: `{self.repo_root.name}`",
            "",
            "This brief answers the five questions every FDE must answer in the first 72 hours.",
            "Each answer is grounded in evidence from static analysis and LLM inference.",
            "",
            "---",
            "",
        ]

        for qid, question in DAY_ONE_QUESTIONS.items():
            answer = self.day_one_answers.get(qid, "_(LLM analysis not available — run without --static-only)_")
            lines += [
                f"## {qid}: {question}",
                "",
                answer,
                "",
                "---",
                "",
            ]

        # Appendix: structural stats
        lines += [
            "## Appendix: Structural Statistics",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total modules | {mg.G.number_of_nodes()} |",
            f"| Module import edges | {mg.G.number_of_edges()} |",
            f"| Tracked datasets | {len(lg.get_dataset_nodes())} |",
            f"| Tracked transformations | {len(lg.get_transformation_nodes())} |",
            f"| Circular dependency groups | {len(mg.find_circular_dependencies())} |",
            f"| Documentation drift flags | {len(self.drift_flags)} |",
            "",
            "---",
            "",
            "_Generated by [Brownfield Cartographer](https://github.com/your-org/cartographer)._",
        ]

        return "\n".join(lines)